### PR TITLE
#27: add sound notification on auto-battle-button activation

### PR DESCRIPTION
**Pull request by bloerwald**

### CODE REVIEW

**Comment by axc450** [comment]
Is this disabled by default? 🙂

**Comment by axc450** [comment]
Also needs a changelog entry please!

**Comment by nicpot** [comment]
Yes thanks - the zip worked as expected and I did not get any errors :)

Much appreciated!

**Comment by bloerwald** [comment]
> Is this disabled by default? 🙂

The default is disabled, sound=none.

https://github.com/axc450/pbs/commit/cc72a1fed6a14c0994768cd048a111928ec78f1e#diff-ad9cc2522727e9a4d23716ad4107ce590459f06f167d808f88a8c10537a0bac0R40-R41

**Review by axc450 — APPROVED** [review]

**Pull request merged**
