### PR TITLE
Update Director:BuildScript action,condition matching

### PR DESCRIPTION
**Pull request by gizzmo**
This change makes the markup a little relaxed. Before, a single single space was required between the action and the start of the condition bracket. If more than one space was present after the action, it would fail with the error `Invalid Action` as the action string had trailing spaces. (yeah maybe a well placed `action:trim()` would've probably worked too, but this fixes it at the source)

Following example is valid, and will parse as expected:
```
change(#2)            [ self(#3).active  ]
use(Emerald Bite:525) [ enemy.hp < 454   ]
use(Emerald Dream:598)[ enemy(#2).active ]
```

Also has the added benefit of triggering the `Invalid Line` error instead of `Invalid Condition` if someone were to construct the line wrong.

Tested with `/dump PetBattleScripts:GetModule('Director'):BuildScript('use(#3)   [ self(#3).active ]')`

### CODE REVIEW

**Comment by gizzmo** [comment]
Figured you'd want a screenshot of this working. Fresh install with only this change applied.

**Comment by bloerwald** [comment]
Was there a reason to not do the same for the `f(x)` parser, i.e. allow `use    (strong) [ kill ]`? If no, I suggest adding

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 89af36b..03aca14 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -2,7 +2,7 @@
 
 ### Fixes
 
-- Allow a dynamic number of spaces between action and condition to allow both `do(x)   [ yes ]` and  `do(x)[yes]`.
+- Allow a dynamic number of spaces between action and condition to allow both `do  (x)   [ yes ]` and  `do(x)[yes]`.
 
 ## v1.8
 
diff --git a/Core/Util.lua b/Core/Util.lua
index 9591983..fe3f27d 100644
--- a/Core/Util.lua
+++ b/Core/Util.lua
@@ -16,7 +16,7 @@ function Util.ComparePet(owner, index, pet)
 end
 
 function Util.ParseQuote(str)
-    local major, quote = str:match('^([^()]+)%((.+)%)$')
+    local major, quote = str:match('^([^()]-)%s*%((.+)%)$')
     if major then
         return major, Util.ParseID(quote) or quote
     end
```

**Review by bloerwald — CHANGES_REQUESTED** [review]
Needs decision on skipping spaces in `f  (x)`, but otherwise ready to merge.

**Comment by axc450** [comment]
Other major languages support this, so I think it is OK! :)

**Comment by gizzmo** [comment]
> Was there a reason to not do the same for the `f(x)` parser

Honestly never thought about that. I just liked the idea of aligning multiple lines of conditions.

> Other major languages support this, so I think it is OK! :)

Well if Lua allows it, than why not.

**Review by bloerwald — APPROVED** [review]

**Pull request merged**
